### ISSUE TITLE
brmenu: menu unresponsive after selection in fullscreen

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#36] opened 2012-09-26 09:48 UTC
@danrossi - this might be something in the site because I cannot reproduce it in my on setups:

http://flash.flowplayer.org/demos/plugins/streaming/brmenu.html
1. start playing
2. go fullscreen
3. select bitrate
4. exit fullscreen
5. try to select bitrate: menu unresponsive

Also in the standalone minimal version:
http://flowplayer.org/demos/plugins/streaming/brmenu.html

Works in my setups:
http://flowplayer.blacktrash.org/test/brmenu.html
and:
http://www.blacktrash.org/underdogma

Things I already checked:
- not related to `autoPlay: false`
- not related to no html splash image
- not related to A tag as player container (well, the site demo uses DIV too)

So far please don't change anything in the code, but help find out what's the issue on the site.

**Comment by phloxic** [comment] 2012-09-26 09:52
Yet another thing only happening in the site demo:
1. start playing
2. select bitrate
3. go fullscreen
4. select bitrate: menu is in wrong position

This almost looks like some css influences the menu plugin???

**Comment by phloxic** [comment] 2012-09-26 09:58
It's also not happening with embedded players, even on Facebook. So far only in the demo at flowplayer.org

@lakshmivyas - perhaps you can have a look as well, both
http://flash.flowplayer.org/demos/plugins/streaming/brmenu.html (broken behavior)
and
http://flowplayer.blacktrash.org/test/brmenu.html (works)
use minimal html, css, javascript, yet the site demo behaves erratically.

See also: http://flash.flowplayer.org/forum/5/103825

**Comment by danrossi** [comment] 2012-09-26 12:52
I honestly don't get it, there was a small code change in the menu plugin but I tested it and was fine. I'll have to have another look so sorry about that.

**Comment by phloxic** [comment] 2012-09-26 14:00
Right now I don't believe it's caused by anything in any plugin. Don't panic ;-) In my working setups I use exactly the same swfs as the site does. As I said, before we/you do any changes to the swfs, let's first find out what triggers this.

So far this is a complete mystery to me.

**Comment by phloxic** [comment] 2012-09-26 14:02
@danrossi - Assigned it to myself to lower your stress levels ;-) Which should not keep you from having an inspiration as to what's causing this.

**Comment by phloxic** [comment] 2012-09-27 20:12
Complete riddle to me:
http://flowplayer.blacktrash.org/test/brmenu.html works
http://flowplayer.blacktrash.org/test/brmen-bug.html does not  - it's not using anything from flowplayer.org! the same js and swf as the working demo

**Comment by phloxic** [comment] 2012-09-27 20:18
GOTCHA! It's enough to specify a position:

``` js
menu: {
  right: 10,
  // more menu config
}
```

and the problem disappears!

@danrossi - so there is a glitch with the plugin in the default positioning. Handing over to you.

**Comment by danrossi** [comment] 2012-09-28 00:45
http://flowplayer.blacktrash.org/test/brmenu-bug.html this shows it in the right place.

**Comment by danrossi** [comment] 2012-09-28 00:45
And it's also working locally I just checked before.

**Comment by phloxic** [comment] 2012-09-28 07:13
Did you really follow the steps 1 thru 5 in the original report?  - I can demo it on Skype.

As for the other symptom described in the followup post:
http://d.pr/i/jWEA

**Comment by danrossi** [comment] 2012-09-28 07:45
Yes its all fine here.

**Comment by phloxic** [comment] 2012-09-28 08:52
Workaround confirmed by user: http://flash.flowplayer.org/forum/5/103825#post-103887

**Comment by danrossi** [comment] 2012-09-28 09:50
Confirmed it's a regression caused by fixes in issue #7, I'll have a look at the position code.

**Comment by danrossi** [comment] 2012-10-01 05:38
Still cannot replicate on my end you likely have a wrong version again :(

https://dl.dropbox.com/u/3394987/menufs.png
https://dl.dropbox.com/u/3394987/menunormal.png

Try this if possible

https://dl.dropbox.com/u/3394987/flowplayer.menu-3.2.11.zip

**Comment by phloxic** [comment] 2012-10-01 10:17
1. I am using the release version, exactly the same binary as what's distributed - the bug is present on the site too. http://releases.flowplayer.org/swf/flowplayer-3.2.11.swf, http://flowplayer.blacktrash.org/flowplayer.menu-3.2.11.swf and the flowplayer.menu-3.2.11.swf from http://releases.flowplayer.org/flowplayer.menu/flowplayer.menu-3.2.11.zip do not differ.
2. https://dl.dropbox.com/u/3394987/flowplayer.menu-3.2.11.zip exhibits the same buggy behavior here, although it's a different binary than the distributed one - emptied cache, verified use of your plugin in network console. Again, it can be worked around by giving a positional parameter in the menu config.

The screenshots do not help because I can't tell whether in the case of https://dl.dropbox.com/u/3394987/menufs.png you selected a different rate in non-fullscreen mode and in the case of https://dl.dropbox.com/u/3394987/menunormal.png you followed the steps in the original report ;-)

**Comment by danrossi** [comment] 2012-10-01 10:20
I dont understand, the menu is displaying in the right position for me, and the bitrate selections are different to display changing bitrates and yes I followed the steps above cannot replicate here I'm afraid. 

Update:

The test file had this in it sorry

width: 300,
right: 0

**Comment by danrossi** [comment] 2012-10-01 10:38
I'll provide a little work around here to adjust when going in and out of fullscreen.

**Comment by danrossi** [comment] 2012-10-01 10:43
OK that seems to work fine, or we can also set a default of right: 0 to the positioning as a safety measure also.

**Comment by danrossi** [comment] 2012-10-01 10:49
The issue is it positions once its been added to the stage but will not attempt again or it will be trying to attempt to reposition each times it's opened and only trying again during a fullscreen event is the best bet. 

https://dl.dropbox.com/u/3394987/flowplayer.menu-3.2.11.zip sorry about that.

**Comment by phloxic** [comment] 2012-10-03 15:21
https://dl.dropbox.com/u/3394987/flowplayer.menu-3.2.11.zip works for me. thx.

**Comment by danrossi** [comment] 2012-10-04 17:13
not a problem sorry about the fuss, sometimes the test files in the sources have extra configs I dont see until its too late.

**Comment by danrossi** [comment] 2013-02-24 11:04
closing for now

**Closed as completed by danrossi** 2013-02-24 11:04 UTC
Labels: ready for testing
