### ISSUE TITLE
3.2.17 dev: hw accel shows branding

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#156] opened 2013-11-22 17:46 UTC
http://flash.dev94.flowplayer.us/demos/configuration/accelerated.html
The screen branding bottom left should only appear during load.

**Comment by danrossi** [comment] 2013-11-23 04:03
the stage video mask indexing has crapped out again as it was confirmed to be working before.

**Comment by danrossi** [comment] 2013-12-04 13:11
The changes from way back in february are missing, it looks like the merge never happened or got lost. Its in the commit logs.

**Comment by danrossi** [comment] 2013-12-04 13:12
closing this, and revert back to #75.

**Closed as completed by danrossi** 2013-12-04 13:12 UTC
Labels: bug
