### ISSUE TITLE
Inconsistent scrubbing/seeking behaviour, especially in paused state

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#145] opened 2013-11-07 13:57 UTC
With rtmp.

scrubbing issues:
1. start playback
2. pause
3. scrub fast to various positions
4. time tooltip is not properly updated or resume happens at a surprising/different position

clicking issues:
1. start playback
2. pause
3. click anywhere on timeline
4. nothing happens

Works most of the time after a scrub.

Best tested with longer videos:
http://flowplayer.blacktrash.org/test/rtmp.html
http://flash.flowplayer.org/demos/standalone/plugins/streaming/bwcheck-smil.html

Here's a screencast by a customer:
EDIT: removed on customer's demand

**Comment by ViliusS** [comment] 2013-11-07 14:03
I can confirm this behaviour. Also similar inconsistencies can be seen at JavaScript level -> https://github.com/flowplayer/flash/issues/90

Sometimes onStart event is fired before onBegin. On resume sometimes onBegin is fired, sometimes not. Etc.

**Comment by phloxic** [comment] 2013-11-13 08:53
Another symptom:
When one _is_ able to seek in paused state sooner or later the loading animation is visible at the same time as the pause button. The player _looks_ like it's in loading and paused state at the same time (it is actually in paused state 4).

**Comment by danrossi** [comment] 2013-11-23 07:45
scrubbing is fine when paused the time updates correctly. the controls disables clicking the scrub bar  when paused. please confirm if this needs to be enabled.

**Comment by phloxic** [comment] 2013-11-23 11:17
It's better with 3.2.17 dev, but not always:
![seeksync](https://f.cloud.github.com/assets/168338/1606332/d4cc55da-5431-11e3-9f27-55ba3716f0bb.jpg)

And: clicking the scrub bar when paused now _does_ work, although with sometimes strange results.

**Comment by danrossi** [comment] 2013-11-25 04:30
The time update is stopped when paused which makes sense but should update when there is a seek. There is two places this needs to happen on the scrubber tooltip and on the time display. So force an update when there is a seek and paused should do it. There shouldn't be a reason these be running when paused still though.

**Comment by danrossi** [comment] 2013-11-25 04:45
There is already something in there to do this lol, however it needs to force an update after a seek complete not seek start.

**Comment by danrossi** [comment] 2013-11-25 04:47
there is no seek complete event to use.

**Comment by danrossi** [comment] 2013-11-25 04:53
I'll do it on a metadata update but keep the original code in there also just in case.

**Comment by danrossi** [comment] 2013-11-25 04:57
The scrubber needs to be clickable when paused still, something is stopping it it's active and enabled though.

**Comment by danrossi** [comment] 2013-11-25 06:53
https://dl.dropboxusercontent.com/u/3394987/flowplayer.controls-3.2.15.zip. Too much variations to make the trackbar clickable when paused but the dragger does the same thing. This will update correctly. The issue is there is no seek complete player event and the time gets updated at the point of seek start not end.

**Comment by danrossi** [comment] 2013-11-25 08:04
I'm getting to that one just discovered it trying to close that other ticket no worries. Its not supplying any update at all.

**Comment by danrossi** [comment] 2013-11-25 08:06
Not assigned to me.

**Comment by anssip** [comment] 2013-11-25 09:29
I'll test with Dan's latest fix. Automatic updates by Gitbot are not live yet. I should have them working today.

**Comment by phloxic** [comment] 2013-11-27 09:52
See http://flowplayer.org/forum/#!/plugins#flashplayer-issues (2.)

**Closed as completed** 2013-12-03 13:41 UTC
Labels: wontfix, ready for testing
