### ISSUE TITLE
OVA Plugin With Mid as Option

### ISSUE THREAD

**Issue by shishir12** [flowplayer/flash#46] opened 2012-10-26 07:34 UTC
We are using OVA Plugin to show Ads while streaming.

We have a problem with the plugin when mid-roll is selected, the original video does not start after the Ad clip is played completely or when skipped. The player hangs.

To see a demo of the same follow the steps given below,
1. Use the html sample given below.
2. Play the video.
3. Wait for 5 secs until the Ad starts.
4. Click on skip ad.
5. Player hangs, page has to be refreshed.

<html>
    <head>
        <title>OVA Sample</title>
        <script type="text/javascript" src="flowplayer-3.2.6.min.js"></script>
    </head>
    <body>

```
    <div  id="player" class="player"></div>

    <script>
        flowplayer('player', { src: 'http://static.demo.vasop.com/libraries/flowplayer/flowplayer.commercial-3.2.15.swf', wmode: 'opaque' }, {
            "playlist": [
                {
                    "url": "http://content.bitsontherun.com/videos/wDqjiZXZ-m0JsjUy0.mp4"
                }
            ],
            "plugins": {
                "controls": {
                    "autoHide": "never"
                },
                "ova": {
                    "url": "http://static.demo.vasop.com/libraries/flowplayer/ova-trial.swf",
                    "ads": {
                        "skipAd": {
                            "enabled": "false"
                        },
                        "servers": [
                          {
                            "type": "OpenX",
                            "apiAddress": "http://openx.openvideoads.org/openx/www/delivery/fc.php"
                          }
                        ],
                        "schedule": [
                          {
                               position: "mid-roll",
                                startTime: "00:00:05",
                                zone: 5
                            }
                        ]
                    },
                    "debug": {
                        "levels": "fatal, config, vast_template, http_calls"
                    }
                }
            }
        });
    </script>
</body>
```

</html>

Please let me know if anything we need to do to fix the problem.

Any help is appreciated.

**Comment by ViliusS** [comment] 2012-10-26 07:58
Probably a duplicate of https://github.com/flowplayer/flash/issues/42 ? Also please see a discussion at http://flash.flowplayer.org/forum/7/104184

**Comment by danrossi** [comment] 2012-10-26 08:02
Hi there is an error thrown which you wont get if you have the debug player it looks like a problem with ova inside the clipdone listener are you able to report this there

**Comment by danrossi** [comment] 2012-10-26 08:03
TypeError: Error #1009: Cannot access a property or method of a null object reference.
    at MethodInfo-1561()
    at EventListener/notify()
    at org.flowplayer.model::EventDispatcher/_dispatchEvent()
    at org.flowplayer.model::EventDispatcher/http://flowplayer.org/core/internal::doDispatchEvent()
    at org.flowplayer.model::ClipEventDispatcher/dispatchEvent()
    at PlayState/onClipDone()
    at EventListener/notify()
    at org.flowplayer.model::EventDispatcher/_dispatchEvent()
    at org.flowplayer.model::EventDispatcher/http://flowplayer.org/core/internal::doDispatchBeforeEvent()
    at org.flowplayer.model::Clip/onBeforeClipEvent()
    at EventListener/notify()
    at org.flowplayer.model::EventDispatcher/_dispatchEvent()
    at org.flowplayer.model::EventDispatcher/http://flowplayer.org/core/internal::doDispatchBeforeEvent()
    at org.flowplayer.model::ClipEventDispatcher/dispatchBeforeEvent()
    at AbstractDurationTrackingController/durationReached()
    at flash.events::EventDispatcher/dispatchEventFunction()
    at flash.events::EventDispatcher/dispatchEvent()
    at PlayTimeTracker/completelyPlayed()
    at PlayTimeTracker/checkCompletelyPlayed()
    at PlayTimeTracker/checkProgress()
    at flash.utils::Timer/_timerDispatch()
    at flash.utils::Timer/tick()

**Comment by shishir12** [comment] 2012-10-26 08:04
We have reported a problem in flowplayer forum as well ans awaiting a reply from them

**Comment by phloxic** [comment] 2012-10-26 08:06
@shishir12 - It works with flowplayer-3.2.14 - see: http://flash.flowplayer.org/forum/5/104191#post-104235
@danrossi - can you contact longtail?
`skipAd` also does not work, not even in 3.2.14 - investigating which version breaks.

**Comment by shishir12** [comment] 2012-10-26 10:04
The issue got solved by downgrading flowplayer version to 3.2.14

**Comment by danrossi** [comment] 2012-10-27 18:15
@christian my only contact is paul I have let him know about it, but again they have a support form, and they usually go directly to paul also.

**Comment by danrossi** [comment] 2012-10-28 05:00
He says he's having a look at it, it's most likely caused by an issue added to fix a problem when going from different providers in a playlist but I need Paul to confirm that. there is definitely an error when it finishes anyway because of something missing.

**Comment by danrossi** [comment] 2012-10-28 15:57
https://dl.dropbox.com/u/3394987/flowplayer-3.2.15.zip please test if this works, if so I'll have to fix an earlier change.

**Comment by shishir12** [comment] 2012-10-29 04:42
The issue is solved using the above mentioned swf files.

**Comment by danrossi** [comment] 2012-10-29 09:22
It's the same problem as #42 may I close this and move it over there if possible.

**Comment by danrossi** [comment] 2012-10-29 12:34
Please check here https://github.com/flowplayer/flash/issues/42

**Closed as completed** 2012-10-29 12:34 UTC
Labels: duplicate
