### ISSUE TITLE
Red5 doen't work rtmp live ..

### ISSUE THREAD

**Issue by AstinCHOI** [flowplayer/flash#107] opened 2013-05-27 17:43 UTC
Hello,
I'm red5 user and flowplayer light user. (will buy your licence.) 

But when I use rtmp live with red5,
I cannot well play rtmp live.

Only to play rtmp live with red5 is that play button clicks many times. Please check this bug please.

I referenced here http://flash.flowplayer.org/plugins/streaming/rtmp.html

but it didn't work.

**Comment by willwh** [comment] 2013-05-27 17:45
Can you provide a stream location to test with? Can you provide some error data from red5? Also your flowplayer config?

**Comment by AstinCHOI** [comment] 2013-05-27 17:58
I just use pure red5-server-1.0

and just follow this section for live streaming http://flash.flowplayer.org/plugins/streaming/rtmp.html

**Comment by AstinCHOI** [comment] 2013-05-27 17:59
$f("red5", "{{ STATIC_URL }}swf/flowplayer-3.2.16.swf", {
        clip: {
            url: '..',
            //scaling: 'fit',
            live: true,
            provider: 'rtmp'
        },

```
    // streaming plugins are configured under the plugins node
    plugins: {
        // here is our rtmp plugin configuration
        rtmp: {
            url: "{{ STATIC_URL }}swf/flowplayer.rtmp-3.2.12.swf",

            // netConnectionUrl defines where the streams are found
            //serverType: 'red5',
            netConnectionUrl: 'rtmp://ip/oflaDemo',
        }
    },
});
```

**Comment by willwh** [comment] 2013-05-27 18:10
I don't work for flowplayer - I'm just interested - I can't delete your comment.

I did test this with a couple of flash players - you're right - doesn't seem to work with flowplayer. Did work with a basic flash player though.

This was returned in console:

[ERROR] time 11:09:54.880 :: 201, Unable to load stream or clip file, connection failed, clip: '[Clip] 'flowplayer''

**Comment by willwh** [comment] 2013-05-27 18:12
I also get these returned in console just before flowplayer fails:

POST http://ip:0/fcs/ident2  ip:0/fcs/ident2:1
POST http://ip:0/open/1  ip:0/open/1:1

**Comment by AstinCHOI** [comment] 2013-05-27 18:16
If you click many times, it work remarkably.

**Comment by AstinCHOI** [comment] 2013-05-27 18:16
(play buttons)

**Comment by AstinCHOI** [comment] 2013-05-27 18:33
I found the stupid solution

You can append, 
setTimeout("$f().pause()", 1000);
    setTimeout("$f().pause()", 1500);
    setTimeout("$f().pause()", 2000);
    setTimeout("$f().play()", 3000);

this code,

will play !!

**Comment by danrossi** [comment] 2013-05-27 19:45
The code above is telling to stop the playback, as pause will trigger to close the stream. Can you check your logs on the server and perhaps update to the very latest version.

**Comment by danrossi** [comment] 2013-05-27 19:50
The easiest way to check the logs on the server is to increase the filters on the console log appenders config to display more logs. also enable logs on the player and paste it here.

**Comment by AstinCHOI** [comment] 2013-05-28 05:11
I checked logs, but it's same as done to undone(bug). Only to play with flowplayer is many clicks like above scripts.

**Comment by AstinCHOI** [comment] 2013-05-28 06:40
I used pure red5 server.

**Comment by danrossi** [comment] 2013-05-28 11:46
Please paste it here as I dont understand what you just said sorry.

**Comment by AstinCHOI** [comment] 2013-05-28 12:08
When I play with flowplayer, flowplayer didn't answer any error logs.
Pure Red5 Server which sets nothing is also didn't answer any error logs.

Did you test flowplayer rtmp with red5-server?
I will try to paste the log.
Wait ..

**Comment by AstinCHOI** [comment] 2013-05-28 12:20
{objectEncoding=3, app=oflaDemo, fpad=false, flashVer=MAC 11,7,700,203, tcUrl=rtmp://secret/oflaDemo, audioCodecs=3575, videoFunction=1, pageUrl=http://[secret], path=oflaDemo, capabilities=239, swfUrl=http://secret/static/swf/flowplayer-3.2.16.swf, videoCodecs=252}
[INFO] [NioProcessor-6] org.red5.server.net.rtmp.RTMPHandler - Remembering client buffer on stream: 3000
[INFO] [pool-4-thread-2] org.red5.demos.oflaDemo.Application - W3C x-category:stream x-event:play c-ip:secret x-sname:c2eb4ad5-9e75-4d83-af25-d02c364972fc
[INFO] [NioProcessor-6] org.red5.server.stream.ClientBroadcastStream - Consumer connect
[INFO] [pool-4-thread-4] org.red5.demos.oflaDemo.Application - W3C x-category:stream x-event:play c-ip:secret x-sname:c2eb4ad5-9e75-4d83-af25-d02c364972fc x-name:856b2b57295f9984614a66239d6bdb45

This is my red5 log when i play with flowplayer.
You can install red5-server easily. Why don't you test on your computer ?

And I put the client code as tutorial as http://flash.flowplayer.org/plugins/streaming/rtmp.html 
perfectly same.

Other flash player(provided red5 player : your_red5_ip:5080 if you install, you can check) well to play.

**Comment by AstinCHOI** [comment] 2013-05-28 12:22
The interesting is when I click play or pause button many times like

setTimeout("$f().pause()", 1000);
setTimeout("$f().pause()", 1500);
setTimeout("$f().pause()", 2000);
setTimeout("$f().play()", 3000);

this script, it works remarkably.

**Comment by AstinCHOI** [comment] 2013-05-28 12:23
And I broadcasted for live.
What do you want information?
I need the help to correct this bug for flowplayer.

**Comment by danrossi** [comment] 2013-06-03 15:28
Am unable to build red5 please provide working demo thanks

**Comment by danrossi** [comment] 2013-06-04 14:06
I am now able to run the server it was caused by a logging library conflict on osx and will test.I have direct contact with them just in case its a problem on their end but do try to use the trunk version to be on the same page but i will try 1.1 first

**Comment by danrossi** [comment] 2013-06-04 17:22
red5 plays  fine with both vp6 and h264, however with vp6 it doesn't trigger metadata which I fixed for a different ticket. 

https://dl.dropboxusercontent.com/u/3394987/flowplayer.rtmp-3.2.12.zip try this if possible if you are publishing a vp6 stream. 

your filename also needs no prefix on it like other servers would so url: "livestream"

**Comment by danrossi** [comment] 2013-11-19 10:43
closing this for now.

**Closed as completed by danrossi** 2013-11-19 10:43 UTC
Labels: ready for testing
