### ISSUE TITLE
mp4 pseudo: controlbar delays update of time

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#104] opened 2013-05-17 10:25 UTC
1. start playback
2. go into paused state
3. in the console e.g. $f().seek(60)

FLV http://flash.flowplayer.org/demos/standalone/plugins/streaming/index.html - controlbar time updates to new position.
MP4: http://flowplayer.blacktrash.org/test/minimal-pseudo.html - pictures updates to new position, controlbar time does not, both loading animation and play button are visible. - controlbar time is updated after resume.

http://flowplayer.org/forum/#!/moot/12084

**Comment by anssip** [comment] 2013-11-24 13:11
Could not reproduce. With mp4 the seek took quite a bit of time but it eventually finished, buffering animation stopped and the time in controlbar was updated.

@blacktrash please retest this. Could be also related to how the mp4 was encoded.

**Comment by phloxic** [comment] 2013-11-25 07:00
Ok, but `$f().seek()` takes ages (perhaps the pseudo-protocol), also noted here: https://github.com/flowplayer/flash/issues/145#issuecomment-28377824
And when you scrub, you still have divergence between controlbar time and target position time, again also noted here: https://github.com/flowplayer/flash/issues/145#issuecomment-29130540 et. al.

**Comment by danrossi** [comment] 2013-11-25 08:06
Shall I look at this ? The plugin isn't providing a seek update or metadata and therefore unlikely doing a server seek when paused therefore not updating the time. The time display timer is stopped in paused mode.

**Comment by danrossi** [comment] 2013-11-25 09:30
Its related to #630 an old ticket. Seeking on these pseudo streams is slow to begin with because of high latency most likely on hddn ! no idea. Its not updating with the correct event because its stuck in a silent seek even after the dragger is dropped.

**Comment by anssip** [comment] 2013-11-25 09:44
would be good if we can test this with something else than HDDN. Any ideas what we could use here as a server?

**Comment by danrossi** [comment] 2013-11-25 10:34
Let me just get the event working first. It's not attempting a server seek for me. I'm not sure who else does this apart from akamai who have their own plugin.

**Comment by danrossi** [comment] 2013-11-25 11:25
ok #630 was to block requesting too much data when dragging and silent seeking and to only update when dropping the dragger. This is fine when playing but its stuck in silent seek when finish dragging.

**Comment by danrossi** [comment] 2013-11-25 12:37
HDS has issues also, I've found somewhere to force a seek and turn off silence seeking when mousing up, this is fine for both rtmp and pseudo when paused. In here it was just dispatching a seek player event but really the time has not updated yet from the stream and sticks to the old time. Not sure what to do about HDS its not delivering metadata events like the others, i'll see if it has a seek complete event.

**Comment by danrossi** [comment] 2013-11-25 13:04
@anssip core build is broken because of a missing compiler constant secondaryDomains. I believe that was the domain checker for the plugin loader.  the loadercontext may be the answer to only load from the same domain perhaps. 

see

BUILD FAILED
build.xml:12: flowplayer/tld/secondary doesn't exist

**Comment by danrossi** [comment] 2013-11-25 13:33
this is also causing plugin build issues

<arg line="-define+=CONFIG::secondaryDomains,${secondary-domains-quoted}"/>

**Comment by danrossi** [comment] 2013-11-25 13:38
OK I provided a fix that will help for both rtmp / pseudo. HDS needed some special treatment in the core because of this seek timer which i'm still unsure what is for. This has always been a problem a I believe stopping the timer because the returned time for HDS is a fraction less than the seek target so a flooring was required here to make it stop and
 dispatch a seek event. 

I can't compile and update im afraid because above, but its working across all 3 plugins.

**Comment by danrossi** [comment] 2013-11-25 13:59
https://dl.dropboxusercontent.com/u/3394987/flowplayer.controls-3.2.15.zip
https://dl.dropboxusercontent.com/u/3394987/flowplayer-3.2.17-dev.zip

**Comment by anssip** [comment] 2013-12-03 13:50
@blacktrash can you please test this again. Latest versions are in dev.

**Comment by phloxic** [comment] 2013-12-03 14:56
This is looking quite good at http://flash.dev94.flowplayer.us/demos/plugins/streaming/mp4-pseudostreaming.html
Maybe HDDN is just in a good mood ;-)
So: not as snappy as RTMP (obviously), but way more responsive than when I last checked.
:+1:

**Comment by anssip** [comment] 2013-12-04 12:32
Awesome. Closing this now!

**Closed as completed by anssip** 2013-12-04 12:32 UTC
Labels: ready for testing
