### ISSUE TITLE
instream issues

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#105] opened 2013-05-20 15:34 UTC
The simple instream demo at http://flash.flowplayer.org/demos/configuration/instream-playlist.html exhibits these problems:
1. scrubbing to 0 (or leftmost, supposedly 0) starts the feature, not the preroll
2. replay replays the postroll, does not start from the beginning

Additional problems with audio:
1. audio 3.2.10: replay starts feature, not preroll
2. audio 3.2.9 (because 3.2.10 is buggy, see: #78): replay starts preroll, but midroll is omitted (have to check that for video too)

Important for advertising plugins, so maybe contact bigsool.

http://flash.flowplayer.org/forum/2/104868

**Comment by phloxic** [comment] 2013-11-07 14:56
Probably related: #145

**Comment by anssip** [comment] 2013-12-05 12:34
I think issue 1. scrubbing to 0 actually _should_ start the feature, _not_ the preroll.

Cannot reproduce 2. with the current dev version. Also with dev the mid roll is not omitted on replay.

Will check with audio clips next.

**Comment by phloxic** [comment] 2013-12-05 13:07
Confirming that 2. is not happening with dev.
I disagree re: scrubbing to 0. If I scrub to a different position the corresponding clips are played as well.
Be that as it may, scrubbing to 0 in the main clip leaves the playhead fixed at 0 while playback is going on - if you click to pause the pre-roll starts.
That can't be intentional behaviour.

**Comment by anssip** [comment] 2013-12-05 15:45
That issue (scrubbing to zero --> playhead not moving) was not actually related to in stream clips, happened with all kins of clips. That's now fixed.

**Closed as completed** 2013-12-09 14:23 UTC
Labels: bug

**Comment by phloxic** [comment] 2013-12-09 14:48
Why should scrubbing to 0 start the feature? The position of the pre-roll _is_ 0.
