### ISSUE TITLE
bitrateselect + menu + $f().play(clip) makes menu unresponsive

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#7] opened 2012-09-03 15:58 UTC
Demo by user: http://zxc.pp.ua/fptest2/index.html

Sometimes when you trigger play() on a new clip the menu becomes "greyed out" and unresponsive.

See also: http://flowplayer.org/forum/5/103187#post-103187

The example has unversioned swf files, but I diffed flowplayer.swf, flowplayer.bitrateselect.swf, flowplayer.menu.swf successfully against their latest versions (3.2.14, 3.2.12, 3.2.10).

**Comment by danrossi** [comment] 2012-09-03 16:22
The config is a bit messy hence why it's not playing back anything on load but i see the issue when clicking the 3 links no problems.

**Comment by danrossi** [comment] 2012-09-03 17:03
I got him, it's somewhere in the menu plugin when resetting the items when changing playlists this way.

**Comment by danrossi** [comment] 2012-09-03 17:32
https://dl.dropbox.com/u/3394987/flowplayer.menu-3.2.10.zip
https://dl.dropbox.com/u/3394987/flowplayer.bitrateselect-3.2.12.zip

Please try these thanks.

**Comment by SkeLLLa** [comment] 2012-09-04 13:53
Thanks, danrossi. Your files fixed those freezes in menu, but I've spotted a little bug: when I switch from LQ to HQ both LQ and HQ have mark.

**Comment by danrossi** [comment] 2012-09-04 14:40
Hi, I may have mentioned before try and setup an initial config properly its just hanging, try and follow a normal configuration, I saw an issue with your config likely because of it. 

baseUrl: baseClipUrl,
            bitrates: [
                {
                    label: 'LQ',
                    bitrate: 300,

```
                url: "media/Musicclips/5nizza_noviyDen-LQ.mp4",
                width: 320
            },
            {
                label: 'HQ',
                bitrate: 1200,
                isDefault: true,
                url: "media/Musicclips/5nizza_noviyDen-HQ.mp4",
                width: 720
            }
        ],
        urlResolvers: "bitrateselect",
```

just put that in your clip config, and you should be right, ive clicked around on my end and can't reproduce it.

**Comment by SkeLLLa** [comment] 2012-09-05 06:10
Added those lines to clip config, not helped. Here are some screenshots:
http://zxc.pp.ua/fptest2/01.gif - select menu (now clip plays in LQ)
http://zxc.pp.ua/fptest2/02.gif - click on HQ quality
http://zxc.pp.ua/fptest2/03.gif - it switched quality, ... once again click on menu, both HQ and LQ are selected

**Comment by danrossi** [comment] 2012-09-05 15:33
Hi disable the bwcheck plugin if you aren't using it / configuring it and perhaps try again.

**Comment by danrossi** [comment] 2012-09-05 15:41
This is my plugins config

controls: { stop: true },
            menu: {
                    url: "flowplayer.menu.swf",
                    items: [
                        { label: "Quality:", enabled: false }
                    ]
            },
            bitrateselect: {
                url: 'flowplayer.bitrateselect.swf',

```
           hdButton: {
                place: 'both',
                splash: false
            },  
            menu: true,

            onStreamSwitchBegin: function (newItem, currentItem) {
               $f().getPlugin('content').setHtml("Will switch to: " + newItem.streamName +
                " from " + currentItem.streamName);
               console.log("new item", newItem);
            },
            onStreamSwitch: function (newItem) {
               $f().getPlugin('content').setHtml("Switched to: " + newItem.streamName);
            }
        },
        pseudo: {
            url: "flowplayer.pseudostreaming.swf"
        },
        content: {
            url: 'flowplayer.content.swf',
            top: 0, left: 0, width: 400, height: 150,
            backgroundColor: 'transparent', backgroundGradient: 'none', border: 0,
            textDecoration: 'outline',
            style: {
                body: {
                    fontSize: 14,
                    fontFamily: 'Arial',
                    textAlign: 'center',
                    color: '#ffffff'
                }
            }
        }
```

no bwcheck if you want bwcheck please configure it in the resolvers list.

**Comment by SkeLLLa** [comment] 2012-09-05 15:51
Thanks. I'll try later to enable both bwcheck and brselect plugins and update example.

**Comment by SkeLLLa** [comment] 2012-09-06 08:16
Updated example with menu+brselect+bwcheck. See http://zxc.pp.ua/fptest2/index.html?_=9876543210

Sometimes the bug with unresponsive menu  appears again. I can't reproduce correct steps (just clicked on different clips, switched qualities) because it appears not often.
Here is full log of bwcheck and menu that reproduce this bug: http://pastebin.com/Yx977Kuy . Menu came unresponsive on penult clip, and I have duplicate "disabled" LQ on last clip.

**Comment by danrossi** [comment] 2012-09-06 16:37
I can't replicate the problem locally

https://dl.dropbox.com/u/3394987/flowplayer.bitrateselect-3.2.12.zip
https://dl.dropbox.com/u/3394987/flowplayer.bwcheck-3.2.11.zip
https://dl.dropbox.com/u/3394987/flowplayer.pseudostreaming-3.2.11.zip

Try these if possible.

**Comment by danrossi** [comment] 2012-09-20 16:24
everything confirmed fixed now ?

**Comment by danrossi** [comment] 2013-02-24 11:03
closing for now

**Closed as completed by danrossi** 2013-02-24 11:03 UTC
Labels: ready for testing
